### ISSUE TITLE
Error encounterd in wallabag logs

### ISSUE THREAD

**Issue by genma** [YunoHost-Apps/wallabag2_ynh#9] opened 2016-09-26 15:23 UTC
I've checked the wallabag specific logs and I see : 

```
root@minipc:/var/www/wallabag2/var/logs# tail -f prod.log 
[2016-09-26 17:17:05] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ynhpanel.js" (from "https:
//wallabag.mydomain.org/")" at /var/www/wallabag2/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfo
ny\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /ynhpanel.js\" (from \"https://wallabag.mydomain.org/\") at /var/www/wallabag2/ven
dor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /va
r/www/wallabag2/var/cache/prod/appProdUrlMatcher.php:632)"} []
```

Nothing in /var/log/nginx/wallabag.mydomain-error.log

If more information needed, just ask.

**Comment by jeromelebleu** [comment] 2016-09-26 15:28
It's related to the YNH button which should appear at the bottom right of the page. Can you confirm that you didn't see it please?

**Comment by genma** [comment] 2016-09-27 09:24
>It's related to the YNH button which should appear at the bottom right of the page. Can you confirm that you didn't see it please?

Yes i've tested yet and the YNH button doesnt' appear. I've tested other apps. It's ok in Dokuwiki. There's not this button in FreshRSS... Is it a problem (other than some message in logs) that this button doesn't appear?

**Comment by lapineige** [comment] 2016-09-27 18:45
I don't have it too, since a while, but this button was present before.

**Comment by lapineige** [comment] 2016-11-29 21:38
Actually, I have it now, and nothing is raised on the console when loading the page.
@genma is this button present on your side now ?

**Comment by JimboJoe** [comment] 2017-06-03 17:26
Not reproduced with latest version. I propose to close this issue for now; don't hesitate to re-open it, should the situation occur again ;-)

**Closed by JimboJoe** 2017-06-03 17:26 UTC
