### ISSUE TITLE
Selecting the interface language does not work

### ISSUE THREAD

**Issue by juliencognito** [YunoHost-Apps/wallabag2_ynh#2] opened 2016-07-18 16:19 UTC
In the configuration page, when selecting the language, the software records but does not apply. Disconnect / reconnect does not solve the problem: the user interface remains in English.

**Comment by lapineige** [comment] 2016-07-19 19:23
I confirm, it's not working for me too.
On a RPi 3, Yunohost 2.4, Debian Jessie.

**Comment by jeromelebleu** [comment] 2016-07-19 20:29
I've located the issue... which will need some time and learning to be fixed. This is due to the way the user language is set in Wallabag - and more generally as suggested by Symfony.

After some deep research, I think the [following guide](http://symfony.com/doc/current/cookbook/session/locale_sticky_session.html) has been used to implement the locale. At least, these two files - [LocaleListener.php](https://github.com/wallabag/wallabag/blob/master/src/Wallabag/CoreBundle/EventListener/LocaleListener.php) and [UserLocaleListener.php](https://github.com/wallabag/wallabag/blob/master/src/Wallabag/CoreBundle/EventListener/UserLocaleListener.php) - suggest that. Unfortunately, it seems to only set the locale for the user session when using regular login form, not the HTTP basic authentication...

If anyone has some ideas to fix that in a clean way... you're really welcome!! :)

**Comment by lapineige** [comment] 2016-07-19 20:55
Don't we have a way to change a config file manually ?
Can't that be done using the web interface ?

**Comment by tcitworld** [comment] 2016-08-16 18:47
Didn't check how that works and can't test today, but does a `cache:clear` fixes it ?

**Comment by jeromelebleu** [comment] 2016-08-16 19:33
@tcitworld Nope, I don't think it's related to the cache but to how the locale is defined for the session - which is by-passed due to the LDAP authentication...

**Comment by lapineige** [comment] 2016-08-25 21:02
It's working for me since 2.0.7 #5

**Comment by tcitworld** [comment] 2016-08-28 09:34
Great. Can someone else confirm ?

**Comment by JimboJoe** [comment] 2016-08-28 13:54
Unfortunately, it still doesn't work for me with 2.0.7.

**Comment by lapineige** [comment] 2016-08-28 14:00
Strangely, I re-installed it, and now it's no longer working.
But when I updated to 2.0.7 it changed the language.
Maybe is due to the update process ?

**Comment by genma** [comment] 2016-09-26 15:21
New reinstallation. Language is changed. Wallabag stay in English. Changing the themes works.

**Comment by JimboJoe** [comment] 2017-06-03 17:25
Not reproduced with latest version. I propose to close this issue for now; don't hesitate to re-open it, should the situation occur again ;-)

**Comment by JimboJoe** [comment] 2018-07-20 17:46
Not to my knowledge...

**Comment by lapineige** [comment] 2018-07-20 17:52
I did not encounter this bug recently.

**Closed** 2019-05-21 08:16 UTC
Labels: bug, pending

**Comment by nicofrand** [comment] 2022-03-31 07:05
I am still having the issue.

**Comment by lapineige** [comment] 2022-03-31 09:14
You mean you didn't have it, but it appeared after an upgrade ?

**Comment by lapineige** [comment] 2022-03-31 09:22
That is very strange…
