### ISSUE TITLE
Cannot upgrade to 2.5.0.  error: An error occurred inside the app upgrade script

### ISSUE THREAD

**Issue by cloo** [YunoHost-Apps/wallabag2_ynh#148] opened 2022-07-30 18:10 UTC
Upgrading fails Wallabag fails
 
### Context

- Hardware: *Old laptop or computer*
- YunoHost version: 4.3.6.3
- I have access to my server: *direct access via keyboard*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
 
### Logs

https://paste.yunohost.org/raw/pajihogise

**Comment by lapineige** [comment] 2022-07-30 20:18
> apt-get --assume-yes --quiet -o=Acquire::Retries=3 -o=Dpkg::Use-Pty=0 --no-remove --option Dpkg::Options::=--force-confdef --option Dpkg::Options::=--force-confold install php7.4-tidy php7.4-curl php7.4-redis php7.4-mbstring php7.4-ldap php7.4-intl --dry-run
The following packages have unmet dependencies:
php7.4-redis : Depends: php7.4-igbinary but it is not going to be installed
             Breaks: php-redis (< 5.3.7+4.3.0-1+0~20220330.42+debian10~1.gbp6fe8b7~)

Duplicate of #141, probably.

Could you try the latest testing branch (at your own risk) ? If not, just wait a few days, a fix is ongoing ;)

**Closed by lapineige** 2022-07-30 20:18 UTC

**Comment by cloo** [comment] 2022-07-31 15:51
Thanks @lapineige. I guess I'll rather wait for the fix.

**Comment by cloo** [comment] 2022-08-04 19:40
2.5.1 fixed it, thanks.

**Comment by lapineige** [comment] 2022-08-05 16:23
Great :smiley:
