### ISSUE TITLE
Last upgrade 2.5.4 ynh8 broke my web instance

### ISSUE THREAD

**Issue by pp-r** [YunoHost-Apps/wallabag2_ynh#222] opened 2024-10-12 14:33 UTC
### Describe the bug

*After update Wallabag2 from 2.5.4 ynh7 to 2.5.4 ynh8, i couldn't see my instance from the web as the entire instance was delete/unreachable. I couldn't connect my portal page or admin page.*

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.2.30.2
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - Exotic ssh port and https://forum.yunohost.org/t/cannot-log-in-with-latest-wallabag-update/31073/43

### Steps to reproduce

- *Log in the admin panel*
- *Proceed to upgrade Wallabag2*
- *Log out*
- *Web instance unreachable via https but ok with SSH*

### Expected behavior

*What is expected is that after updating Wallabag2 from 2.5.4 ynh7 to 2.5.4 ynh8 i could have my instance online again.*
I should not have to connect through SSH, remove app and restore pre-update Wallabag2 backup ... which it seems to be the solution to make my whole web instance on line again.
~After this, no more update seems available in the web admin panel for Wallabag 2.5.4 ynh8 while i'm with version 2.5.4 ynh7.~

### Logs

https://paste.yunohost.org/raw/eraxawikov

**Comment by lapineige** [comment] 2024-10-12 21:04
Duplicate of #217 and quoted forum post.
Please restore the pre-upgrade backup while waiting for a fix, if the command line fix doesn't fit you.

**Closed by lapineige** 2024-10-12 21:04 UTC
